name: Quarto Publish to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   version: "pre-release"  # (opcional) fija versión de Quarto

      - name: Render site
        run: quarto render   # genera _site/ (o lo que definas en _quarto.yml)

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site        # cambia si definiste otro output-dir

      - uses: actions/deploy-pages@v4
